### ISSUE TITLE
CORS support 

### ISSUE THREAD

**Issue by stevenfirstrowinc** [IdentityModel/Thinktecture.IdentityModel#104]
In the old 4.5 library there was support for CORS configuration.  I don't see that here.  I know that OWIN/WebAPI has support now, but it seems to not support static files where the old IdentityModel.4.5 seemed to.  So the question is twofold:

1.  Will the CORS support from 4.5 be added here?
2.  Is there an alternative way to enable static files CORS support in WebAPI?

Thanks in advance

**Comment by brockallen** [comment]
No, we removed the CORS feature in favor or Web API and Katana's implementation. Read here for the Web API implementation:

https://msdn.microsoft.com/en-us/magazine/dn532203.aspx

**Comment by stevenfirstrowinc** [comment]
so is there someway to allow static files using the Web API & Katana?

**Comment by brockallen** [comment]
The CORS support in Web API is a different one than Katana. If you want support for static files, then look at the Katana implementation. Don't forget to enable RAMMFAR.

**Comment by stevenfirstrowinc** [comment]
we are already using the Katana implementation and we are using both of the following

            app.UseStaticFiles();
            app.UseFileServer();

**Comment by brockallen** [comment]
You'd have to get docs from Microsoft for the Katana middleware (or read the source code, which is what I'd do to use it).

**Comment by stevenfirstrowinc** [comment]
Thanks for the help Brock.  In case anyone else has the issue this is what I did

    app.UseStaticFiles(new StaticFileOptions
            {
                OnPrepareResponse = context => context.OwinContext.Response.Headers.Set("Access-Control-Allow-Origin",
                    context.OwinContext.Request.Headers.Get("Origin"))
            });

Plus RAMMFAR
