### ISSUE TITLE
NullReferenceException in ConfigureFam when using local IIS

### ISSUE THREAD

**Issue by Epicycle23** [IdentityModel/Thinktecture.IdentityModel#106]
Hello,

when i am switching from IIS-Express to Local-IIS i get a null reference exception during ConfigureFam.
Is there anything i am missing?
Working with IIS-Express works just fine.

Stack Trace:
[NullReferenceException: Object reference not set to an instance of an object.]
   Thinktecture.IdentityModel.EmbeddedSts.EmbeddedStsModule.ConfigureFam() in c:\ballen\github\Thinktecture.IdentityModel\source\Thinktecture.IdentityModel.EmbeddedSts\EmbeddedStsModule.cs:52
   Thinktecture.IdentityModel.EmbeddedSts.EmbeddedStsModule.app_BeginRequest(Object sender, EventArgs e) in c:\ballen\github\Thinktecture.IdentityModel\source\Thinktecture.IdentityModel.EmbeddedSts\EmbeddedStsModule.cs:21
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +91
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +164

Best regards
Epicycle

**Comment by brockallen** [comment]
I'm guessing you don't have the HTTP module registered.

**Comment by Epicycle23** [comment]
Yes, thank you that fixed it.
