### ISSUE TITLE
RequestResourceOwnerPasswordAsync is slow.

### ISSUE THREAD

**Issue by ravindrachallagandla** [IdentityModel/Thinktecture.IdentityModel#108]
We are using ThinkTecture to generate token. Below is my code.

var tokenEndpoint = string.Format("{0}/token", ConfigurationManager.AppSettings["WEBSERVICE_URL"]);
                        var client = new OAuth2Client(new Uri(tokenEndpoint));
                        var accessToken = client.RequestResourceOwnerPasswordAsync(userName, loginViewModel.Password).Result.AccessToken;

getting access token takes more than 7 seconds for first time. Is there a way to reduce this time ?

**Comment by leastprivilege** [comment]
Well - you are showing my some client code. No idea what's happening on your server.

**Comment by filipw** [comment]
I think it's safe to close this issue

**Comment by brockallen** [comment]
Thx Filip :P
