### ISSUE TITLE
Windows Security dialog appears when using RequestResourceOwnerPasswordAsync

### ISSUE THREAD

**Issue by mwereda** [IdentityModel/Thinktecture.IdentityModel#110]
I'm using RequestResourceOwnerPasswordAsync from OAuth2Client within my web application. IdentityServer v3 is used as identity provider. 
On one of our test environments when invalid user credentials are passed, Windows Security (on IE) is shown prompting for credentials. On other browsers also such dialog is displayed. On my local machine it works without this dialog being shown (and it's expected behaviour).

What could be the reason why dialog is shown and how to prevent showing it?

**Comment by leastprivilege** [comment]
thats most probably a server setting. make sure Windows auth is disabled.

**Comment by mwereda** [comment]
Yes, this was the reason. But not only Windows auth should be disabled. Basic auth should be disabled as well.
Thank you for your help.
