### ISSUE TITLE
CORS Support in ASP.NET Web API

### ISSUE THREAD

**Issue by plemm98** [IdentityModel/Thinktecture.IdentityModel#111]
Hi,

I'm using thinktecture identity server 1.2 on two differents mvc web site. One is a web api, the other is a simple web site that calling method in the api website.

Both are on different domain. So, in order to call my web api in javascript, i need to setup cors support on my web api web site.

I follow Brock Allan post on the subject "CORS Support in ASP.NET Web API 2", and deploy the nuget package, and add the following line in the webapiconfig file.

config.EnableCors(new EnableCorsAttribute("*", "*", "*"));

But, when i try to call my webapi, i receive this error message.

OPTIONS http://localhost:96/helloapi/hello (anonymous function)
XMLHttpRequest cannot load http://localhost:96/helloapi/hello. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:51954' is therefore not allowed access. The response had HTTP status code 405.

But, in the startup file, if i add this line of code

app.UseCors(CorsOptions.AllowAll);

I can call my web api with no problem.

A lot of people on the web say this is the only way to make it work. Not totally sure about that.

Of course, if i include the "Access-Control-Allow-Origin" header manually during a webapi request, it also work.

So, i'm pretty sure i'm not implementing the cors support correctly in my solution. Beside adding the nuget package in the webapi solution, and adding the config.enablecors() method in the webapiconfig, is there something else i need to turn on to make it work properly? 

Here's an example how i'm calling the web api -

var xhr = new XMLHttpRequest();
xhr.open("GET", "http://localhost:96/helloapi/hello", true);
xhr.setRequestHeader("Authorization", "Bearer " + "512652fa32c9f1736da8dfdcf09d862c");
xhr.send();

Best regards,

**Comment by OzBob** [comment]
Excellent CORS question - I am following along to see the answer.
Is it possible for the two servers to be 'subdomains' of a shared domain?  auth.mydomain.com, and api.mydomain.com, a possible work around?

**Comment by brockallen** [comment]
This is a question about Microsoft's CORS library, not IdentityModel, right?

**Comment by plemm98** [comment]
I hope so.

Is there an other place you have in mind i should post this question then?

Best regards,

**Comment by brockallen** [comment]
The MSDN and/or ASP.NET forums?

**Comment by plemm98** [comment]
Fast, accurate answers.

You may close/remove/destroy/annihilate/obliterate this issue in that case. 

Best regards,
