### ISSUE TITLE
ClaimsAuthorizeSample broken

### ISSUE THREAD

**Issue by agray** [IdentityModel/Thinktecture.IdentityModel#113]
I cannot get this solution to compile as it stands.  I have tried updating nuget packages without success.

After updating packages It complains about conflicts in referenced Newtonsoft.Json version and can't find ClaimsAuthorise or ClaimsAuthoriseAttrubite classes.

Please advise.

**Comment by leastprivilege** [comment]
I updated the sample. thanks.

That's a newer version: https://github.com/IdentityModel/Thinktecture.IdentityModel/tree/master/samples/OWIN/ResourceAuthorization
