### ISSUE TITLE
Inconsistent publickeytoken between ResourceAuthorization nuget packages.

### ISSUE THREAD

**Issue by plemm98** [IdentityModel/Thinktecture.IdentityModel#114]
In my web application, i install the Thinktecture.IdentityModel.Owin.ResourceAuthorization.Mvc nuget package version 2.0.0.0.  

The Thinktecture.IdentityModel.Owin.ResourceAuthorization.Mvc.dll is sign using the publickeytoken 4eb3efabd3951a28.

But, the latest version of the  Thinktecture.IdentityModel.Owin.ResourceAuthorization nuget package (Version 1.1.0) is not. 

<i>Thinktecture.IdentityModel.Owin.ResourceAuthorization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null</i>

Same goes for the Thinktecture.IdentityModel.Owin.ResourceAuthorization.WebApi nuget (Version 3.0.0).

<i>Thinktecture.IdentityModel.Owin.ResourceAuthorization.WebAp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null.</i>

So, when building my application, i receive this error message 

<i>Could not load file or assembly &#39;Thinktecture.IdentityModel.Owin.ResourceAuthorization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=4eb3efabd3951a28&#39; or one of its dependencies. The located assembly&#39;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)</i>

Is it possible to compile the Thinktecture.IdentityModel.Owin.ResourceAuthorization.Mvc nuget package without the publickeytoken=4eb3efabd3951a28 so that all nuget packages have the same public key ?

Best regards,

**Comment by leastprivilege** [comment]
We don't sign our assemblies.

**Comment by plemm98** [comment]
I just create an empty mvc site and install your package, and you are right.

I don't see the publickeytoken, so it's must something on my end.

Best regards,
