### ISSUE TITLE
Error when doing Install-Package Thinktecture.IdentityModel.WebApi

### ISSUE THREAD

**Issue by CallumVass** [IdentityModel/Thinktecture.IdentityModel#116]
When I try and install via Nuget I get the following error: Failed to add reference to 'System.IdentityModel'. Please make sure that it is in the Global Assembly Cache.

I'm running on .NET 4.5.1 so I'm not sure why I am getting the error? Any help is appreciated. Thanks

**Comment by brockallen** [comment]
I just tried and it worked for me. Perhaps enable verbose logging in the nuget window and see if that helps track down the issue.

**Comment by CallumVass** [comment]
Hi,

I upgraded to .NET 4.5.2 and it seemed to solve the problem. Thanks.
