### ISSUE TITLE
Upgrade from Web API 1 

### ISSUE THREAD

**Issue by benfoster** [IdentityModel/Thinktecture.IdentityModel#117]
Hey guys,

We've finally got round to upgrading our API to Web API 2.2. Previously we were using Thinktecture.IdentityModel's `AuthenticationHandler` providing Basic, Session Token and Access Key (API Key) based authentication.

What's the best course of action for upgrade? Should we now use the new OWIN Packages? I've installed `Thinktecture.IdentityModel.WebApi.AuthenticationHandler` but it looks like SessionTokenConfiguration has changed somewhat.

Below show's our previous configuration. The signing key used to be a string. Now it looks like it needs a byte array? Also `DefaultAuthenticationScheme` has gone. Finally it looks like the `AuthenticationType` set when using Session Tokens has changed from "JWT"?

        public void Configure(HttpConfiguration config)
        {
            var auth = new AuthenticationConfiguration
            {
                DefaultAuthenticationScheme = "Basic",
                EnableSessionToken = true, // default lifetime is 10 hours,
                SendWwwAuthenticateResponseHeader = true,
                SessionToken = new SessionTokenConfiguration
                {
                    SigningKey = Constants.SessionTokenSigningKey
                }
            };

            string requireSslSetting = ConfigurationManager.AppSettings[Constants.RequireSslSettingKey];
            bool requireSsl;
            if (bool.TryParse(requireSslSetting, out requireSsl))
            {
                auth.RequireSsl = requireSsl;
            }
            
            auth.AddBasicAuthentication((username, password) =>
            {
                var membership = membershipServiceFactory();
                return membership.ValidateCredentials(username, password);
            });

            var authHandler = new AuthenticationHandler(auth);
            config.MessageHandlers.Add(authHandler);
        }

**Comment by leastprivilege** [comment]
As I said on Twitter - AuthenticationHandler is not supported anymore for Web API 2.

It might work - or maybe not. I don't know. All features that AuthenticationHandler provided can now be achieved by OWIN middleware.

**Comment by benfoster** [comment]
Okay, I'm going to work through adding each authentication type as middleware. I'm sure a blog post will folllow :)
