### ISSUE TITLE
Question: Use with Shibboleth possible?

### ISSUE THREAD

**Issue by mrchief** [IdentityModel/Thinktecture.IdentityModel#123]
Is it possible to use this for Shibboleth Authentication? Specifically, I would like to use Shibboleth Auth with an existing IdP entirely via configuration within my MVC 5 app (and not rely on Shibboleth SP installation on the web server).

I'm new to this realm so kind of bit stumped as to how to go about this.

**Comment by brockallen** [comment]
IdentityModel is a helper library for missing security related features in .NET. It does not implement security protocols such as SAML2-p. Check this instead:

https://github.com/KentorIT/authservices

**Comment by mrchief** [comment]
Will take a look, thanks!
