### ISSUE TITLE
Web Api Claims Transformation Caching(Technology), Number Claims

### ISSUE THREAD

**Issue by frobozz67** [IdentityModel/Thinktecture.IdentityModel#128]
Have an SPA Application using ADAL JS.
(Microsoft Web Api, Angular, Javascript, C#, Visual Studio 2013 environment)
I get an Access Token for a Web APi that contains nameidentifier claim.
Token is signed with Symmetric Key.
Web Api is called sending Bearer Token.
Web Api validates token.

Now on the Web Api I want to add additional "application" claims.
Claims that are specific to this Web Api and will be used for 
Authorization decisions.

I add the additional claims using:
app.UseClaimsTransformation(new ApplicationClaims.WebApi.Authentication.ClaimsTransformer().Transform);
and making a database call sending nameidentifier claim in order to load the additional claims.

Now, how do I cache these additional claims on the Web Api so I do not
have to take this performance hit on every Web Api request?
What caching technology is best to use? I have read that we are not supposed to use
"SessionAuthenticationModule" with Web Api (server Infinity issue), is this correct?

In terms of additional claims, how many is too many? I have read
"You don't put all that data into claims - that's a typical mistake you make in your first claims project."
I thought all Authorization decisions were supposed to be made using claims so that you would 
not have to make database calls over and over again in the Authorization Manager.
app.UseResourceAuthorization(new ResourceAuthorizationMiddlewareOptions
{
    Manager = new ApplicationClaims.WebApi.Authorization.AuthorizationManager()
});

**Comment by leastprivilege** [comment]
Well - the choice of caching technology depends on many factory - for single server, in mem caching i use System.Runtime.Caching built into .NET.

You would do caching for both the transformer and the authZ manager.

**Comment by frobozz67** [comment]
It would be a web farm for the Web Api.

"You would do caching the authZ manager"
So does that mean you should minimize the number of claims and just do database look ups and cache that info in the authZ Manager?

**Comment by leastprivilege** [comment]
yes - that's how I would do it

**Comment by frobozz67** [comment]
Thank You!
