### ISSUE TITLE
Make ResourceAuthorizationContext customizable for ResourceAuthorization

### ISSUE THREAD

**Issue by akamud** [IdentityModel/Thinktecture.IdentityModel#136]
I am creating a Web Api 2 application using `Thinktecture.IdentityModel.Owin.ResourceAuthorization`, I was taking a look at the source code and I realized I wanted to change the properties available on my `ResourceAuthorizationContext`, I would like to create a custom `Context` and use it for everything related to `ResourceAuthorization`. That way I could add custom properties to be available for my `CheckAccessAsync` method.

My goal is to have something like this:
```C#
public class CustomAuthorizationManager : ResourceAuthorizationManager
{
    public override Task<bool> CheckAccessAsync(CustomResourceAuthorizationContext context)
    {
        // Access my custom properties coming directly from the context
    }
}
```
So I could use a CustomAttribute like this:
```C#
[CustomResourceAuthorize("CustomValue", "MoreCustomValues")]
public class ValuesController : ApiController
{
}
```
I couldn't figure out a way to customize the Context, like I do with the `ResourceAuthorizationManager`, on startup.
The problem seems to be [these extension methods](https://github.com/IdentityModel/Thinktecture.IdentityModel/blob/e6cf193dbffbe1dc3a15848106807983ec503c22/source/Owin.ResourceAuthorization.WebApi/HttpRequestMessageExtensions.cs), they reference the `ResourceAuthorizationContext` class directly.

Does this make sense? Am I missing something or you really can't do this right now?

Just for the record, I asked this on [StackOverflow](http://stackoverflow.com/questions/31859457/how-to-change-resourceauthorizationcontext-from-thinktecture-identitymodel-resou) too.

**Comment by brockallen** [comment]
The string[] params for resources is meant to allow passing more contextual (or custom) information.

**Comment by akamud** [comment]
I see, I guess the names threw me off, but this would indeed work for me. Thanks :)
