### ISSUE TITLE
OAuth2Client does not work with github oauth

### ISSUE THREAD

**Issue by seescode** [IdentityModel/Thinktecture.IdentityModel#140]
Github oauth's https://github.com/login/oauth/access_token endpoint by default returns name/value pairs.  When I try and get the access token I get the following error:

"Unexpected character encountered while parsing value: e. Path '', line 0, position 0."

The reason seems to be that github by default returns back name/value pairs but the oauth client code tries to parse it into json.  Github can also return back json if you pass in the following header: "Accept: application/json".  I could not find a way to set headers using OAuth2Client.

**Comment by leastprivilege** [comment]
Well - then github is violating the OAuth 2.0 spec - but point taken - I will add the accept header.

**Comment by leastprivilege** [comment]
I made the change in the newer repo - see here

https://github.com/IdentityModel/IdentityModel/commit/c727fa2807b6b512b15ab85cacf7fe9d80a99a78

**Comment by leastprivilege** [comment]
can you give that a try and tell me if this is working for you?

**Comment by leastprivilege** [comment]
try this: https://www.nuget.org/packages/IdentityModel/1.2.0

**Comment by leastprivilege** [comment]
OK?

**Comment by seescode** [comment]
Hi, sorry for the lateness, I checked this and was able to get oauth working with github.  Thanks for fixing this so quickly.
