### ISSUE TITLE
RequestAuthorizationCodeAsync - misleading name 

### ISSUE THREAD

**Issue by pawepaw** [IdentityModel/Thinktecture.IdentityModel#142]
Hello,

Why RequestAuthorizationCodeAsync() method which is used to obtain access/refresh token is named  request authorization code? It's not used to request FOR authorization code it is used instead to request WITH authorization code.

https://github.com/IdentityModel/Thinktecture.IdentityModel/blob/e6cf193dbffbe1dc3a15848106807983ec503c22/source/Client.Shared/OAuth2Client.cs#L201

**Comment by leastprivilege** [comment]
Well - this is the naming scheme we chose (Request+GrantType) - I am sorry it confuses you.

**Comment by dmorrison** [comment]
I agree with @pawepaw - these `Request*` names are confusing. Imagine you were new to Identity Server (like me), and you came upon the `RequestRefreshToken()` method. What would that say to you? Would you intuitively think "this method requests a token response using a refresh token" - probably not. 😞
