### ISSUE TITLE
JsonReaderException in TokenResponse

### ISSUE THREAD

**Issue by hasserygh** [IdentityModel/Thinktecture.IdentityModel#143]
The TokenResponse-class throws the following exception:
>A first chance exception of type 'Newtonsoft.Json.JsonReaderException' occurred in Newtonsoft.Json.dll
>
>Additional information: Error reading JObject from JsonReader. Path '', line 0, position 0.

This happens when calling the "/connect/revocation/"-endpoint using in Thinktecture.IdentityServer. This endpoints returns an empty string ("") and the JSON parsing in TokenResponse failes. It's not a big deal since it doesn't change the result, but it's annoying and shouldn't the TokenRespons class check the value before running it through the parser, an empty 200 response should be valid?

Or should this issue be provided to the IdentityServer repo which uses the TokenResponse "wrongly"?

**Comment by leastprivilege** [comment]
The token client and response class are not supposed to be used with this endpoint. They are designed to be used with the token endpoint...
