### ISSUE TITLE
Loop with EmbeddedSts

### ISSUE THREAD

**Issue by willypowwow** [IdentityModel/Thinktecture.IdentityModel#148]
I am getting a querystring too long issue when redirecting to EmbeddedSTS, with many 25s.   I'm wondering if it has to do with hosting on a custom port.

I am not denying authorization to any location.   Here is my IndentityModel config:

```javascript
    <system.identityModel.services>
        <federationConfiguration>
            <wsFederation passiveRedirectEnabled="true" issuer="http://EmbeddedSts" realm="http://localhost:90" requireHttps="false" />
            <cookieHandler requireSsl="false" />
        </federationConfiguration>
    </system.identityModel.services>
```

![image](https://cloud.githubusercontent.com/assets/7863440/11277474/908d9432-8e9b-11e5-9e36-3a08b7807613.png)

**Comment by brockallen** [comment]
Somehow the cookie is not being set, or you're getting redirected to a URL where the cookie is not being sent.

**Comment by willypowwow** [comment]
Thanks,  I realized I was not authorizing access to any location.   It's working properly now, thank you!

**Comment by waltersr** [comment]
I experienced this same issue and it related to authorization, but in a slightly different fashion.  I added authorization settings to my web.config, but I still had the issue.  I was running my site in VS 2015 with IIS Express and did not think about the IIS Express settings.  I had to also select my project in VS and open the Properties tab and set "Anonymous Authentication" to "Enabled.
