### ISSUE TITLE
Resource Authorization in WebApi: OwinContext is null in HttpRequestMessageExtensions.CheckAccessAsync

### ISSUE THREAD

**Issue by sergegommers** [IdentityModel/Thinktecture.IdentityModel#154]
In Owin.ResourceAuthorization.WebApi,  request.GetOwinContext() is null inside  HttpRequestMessageExtensions.CheckAccessAsync.

Modifying the code to get hold of the OwinContext like below solves the issue.

    public static IOwinContext GetOwinContext(this HttpRequestMessage request)
    {
      var context = request.Properties["MS_HttpContext"] as HttpContextWrapper;
      if (context != null)
      {
        return HttpContextBaseExtensions.GetOwinContext(context.Request);
      }
      return null;
    }

Regards,

Serge

**Comment by tstone84** [comment]
Was this ever resolved?  I'm running into the same issue.  Is the above "solution" the only solution?

**Comment by sergegommers** [comment]
The latest tag, 3.0.0 has still the same issue. I don't think they accept pull requests anymore.

**Comment by guwer** [comment]
The code above is a workaround but for me solution was this knowledge:
http://santoshpoojari.blogspot.de/2014/01/known-issue-getowincontext-return.html
Here is more on this:
https://stackoverflow.com/questions/20478381/asp-net-vs-mvc-vs-webapi-and-usetaskfriendlysynchronizationcontext
