### ISSUE TITLE
Deprecated? If so, what is the "replacement" for Client Library?

### ISSUE THREAD

**Issue by LeeDumond** [IdentityModel/Thinktecture.IdentityModel#156]
Seeing as the Thinktecture branding is being removed and this project is deprecated, what should we be using as a replacement for the **HTTP Security / OAuth2 Client Library** that is being actively supported?

Thanks much!

**Comment by brockallen** [comment]
This one: https://github.com/IdentityModel/IdentityModel
And NuGet: https://www.nuget.org/packages/IdentityModel

**Comment by LeeDumond** [comment]
Awesome, thank you

**Comment by mbostwick** [comment]
This really should go on the main page..
