### ISSUE TITLE
Deprecated??

### ISSUE THREAD

**Issue by jachin84** [IdentityModel/Thinktecture.IdentityModel#168]
I am considering using the Thinktecture.IdentityModel package in a WebAPI 2 project. Specifically I'm interested in the ResourceAuthorization attribute. However, I'm reluctant given that Thinktecture.IdentityModel is marked with [deprecated]. Is this package deprecated? If so what does that mean long term, will it still be maintained going forward?

**Comment by leastprivilege** [comment]
We are not working anymore on this library. It is done. Feel free to use the latest nuget or grab the source code.

**Comment by Lumirris** [comment]
Forgive me if I don't understand the conventions of marking something as [deprecated], but I thought that this was done when it was being replaced by something else, or is no longer needed. If this is simply 'done', does it really need to be marked as [deprecated], or is that a way of letting people know not to bother submitting pull requests?

It seems to give people pause (myself included) to even use the associated Nuget package...

**Comment by IDisposable** [comment]
It is considered good manners to mark something deprecated for at least one release before yanking it entirely to give consumers a warning and time to migrate away.

**Comment by leastprivilege** [comment]
It pretty much means it is done and not maintained anymore. If it contains something that works for you, by all means use it!

If you want to make improvements, copy the code and evolve it yourself.

This is a really old code-base and does not apply anymore to current technology. Hence deprecated.
