### ISSUE TITLE
With this deprecated, what should I use for Claims-based Authorization?

### ISSUE THREAD

**Issue by tstone84** [IdentityModel/Thinktecture.IdentityModel#170]
I was looking for a package to handle claims-based authorization to use in conjunction with my IdentityServer3 implementation and came across this.  However, it's deprecated and doesn't really say what should be used instead.

Thanks!

**Comment by leastprivilege** [comment]
It's done. Feel free to use the code.

**Comment by tstone84** [comment]
@leastprivilege Thanks for the quick response per usual!!
