### ISSUE TITLE
Does not work with .NET Core project

### ISSUE THREAD

**Issue by alexandis** [IdentityModel/Thinktecture.IdentityModel#178]
Hi,
i need to find solution for ADFS usage from .NET Core project. Since I am testing on local machine, I don't have access to real ADFS. Hoped to use this project, but it's not compatible with .NET Core... Any suggestions? Thanks.

**Comment by brockallen** [comment]
This is the repo you're looking for: https://github.com/IdentityModel/IdentityModel2

**Comment by alexandis** [comment]
Thank you very much. Installed it. The question now is: how to move from
https://github.com/IdentityModel/Thinktecture.IdentityModel/wiki/EmbeddedSts
to new .NET Core structure?
I'm new to .NET Core and cannot find consistent information about it.
It's no more web.config-based, however, I'd like to know how to 'emulate' this old EmbeddedSts in .NET Core?
Would appreciate some advice :-)

**Comment by leastprivilege** [comment]
WS-Federation is not supported anymore in .NET Core. 

You need to stay on the full .NET Framework if you need those APIs.
