### ISSUE TITLE
Thinktecture.IdentityModel.Owin.ScopeValidation conflicting with Microsoft.AspNet.Cors and refusing my OPTIONS 

### ISSUE THREAD

**Issue by B3nCr** [IdentityModel/Thinktecture.IdentityModel#78]
ASP.NET Cors is returning "WWW-Authenticate:Bearer error="insufficient_scope"" when I try to use an Identity Server access token with a CORS request.

I'm trying to using Thinktecture Identity Server v3 and the implicit flow.

I've got an AngularJS application hosted on https://b3ncr.comms/, IdentityServer v3 on https://b3ncr.auth/ and an api on https://b3ncr.comms.api/

My API is configured as follows.

app.UseIdentityServerJwt(new JwtTokenValidationOptions
{
    Authority = "https://b3ncr.auth:44340/identity"
});

app.RequireScopes("sampleApi");
I successfully login and get a token with the following parameters.

https://b3ncr.auth:44340/identity/connect/authorize?response_type=id_token token
    &client_id=Implicit
    &scope=openid profile sampleApi
    &redirect_uri=https://b3ncr.comms:44341/logon
    &nonce=BLAH
That returns a token as expected and I extract that and try to call my API. When I try to call the api with the token AngularJS makes the following HTTP request:

Request URL:https://b3ncr.comms.api:44342/api/Identity
Request Method:OPTIONS

Accept:*/*
Accept-Encoding:gzip,deflate
Accept-Language:en-GB,en-US;q=0.8,en;q=0.6
Access-Control-Request-Headers:accept, authorization
Access-Control-Request-Method:POST
Cache-Control:no-cache
Connection:keep-alive
Host:b3ncr.comms.api:44342
Origin:https://b3ncr.comms:44341
Pragma:no-cache
Referer:https://b3ncr.comms:44341/
And my API then returns the following headers:

Access-Control-Allow-Headers:Content-Type, Authorization
Access-Control-Allow-Methods:GET,PUT,POST,DELETE,OPTIONS
Access-Control-Allow-Origin:*
Content-Length:0
Date:Mon, 27 Oct 2014 22:48:24 GMT
Server:Microsoft-IIS/8.5
WWW-Authenticate:Bearer error="insufficient_scope"
X-Powered-By:ASP.NET

To me that looks like the OWIN middleware is rejecting that request because the token doesn't contain the scope that the API is requiring and that I requested with my authorize parameters. However if I use the token directly, in Fiddler for example it works perfectly.

Is there a workaround for this at the moment? Perhaps using the IdentityModel.45 project to validate the token instead of the OWIN middleware?

**Comment by radrad** [comment]
Hi, 
I am using IdentityServer3.2.0 and this is how I setup my OWIN Middleware to validate access tokens from IdentityServer v3:
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost:44333/core",
                RequiredScopes = new[] { "read write" },
                ValidationMode = ValidationMode.ValidationEndpoint 
            });

When I post like this** to my Web API Post endpoint:
        [Authorize(Roles = "write")]
        [ResponseType(typeof(Superhero))]
        public HttpResponseMessage Post(PostSuperheroModel postSuperheroModel)

this**:
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" --header "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMzMy9jb3JlIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMzMvY29yZS9yZXNvdXJjZXMiLCJleHAiOjE0NTQ0OTU3MDgsIm5iZiI6MTQ1NDQ5MjEwOCwiY2xpZW50X2lkIjoiaW1wbGljaXRjbGllbnQiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwic3ViIjoiYm9iIiwiYXV0aF90aW1lIjoxNDU0NDkyMTA4LCJpZHAiOiJpZHNydiIsImFtciI6WyJwYXNzd29yZCJdfQ.fwREffMK98P2RjjBmcvWdhQqUP0_4U92uaR5X5h_qLbHqjgHpw20HSxxCjpAlJbd2wjqj2bfue94A4CPUvS3uZo6105mbaJPfTiRkswsJnMd3UJNODBdG6FJQ4NypDuGoIAb7DfZcYgZj6iuan5G-iEp47zxw2WJMtloC_yH-k_W1Ra22Rgy4pn90Z_k-8orets6g6wsqmEe1z7I15RNYGHR_CWsGisq4BN6OULWOXtVoff2KhirOZkvUb5MjiWiG1OF6DjauL8pF4nyvNsn_aPPVjJo1jQjw-lU7b39hiRco14QPEWRhXGqCllf2hduacbai77i_IX3CEDZMZxNxA" -d "{
  \"Name\": \"string\",
  \"RealName\": \"string\",
  \"Universe\": \"Marvel\"
}" "http://localhost:51609/api/SuperHeroes"

I get back this:
{
  "date": "Wed, 03 Feb 2016 09:35:19 GMT",
  "www-authenticate": "Bearer error=\"insufficient_scope\"",
  "server": "Microsoft-IIS/10.0",
  "x-powered-by": "ASP.NET",
  "access-control-allow-origin": "http://localhost:51609",
  "access-control-expose-headers": "WWW-Authenticate",
  "x-sourcefiles": "=?UTF-8?B?RjpcUHJvamVjdHNcU3dhZ2dlckRlbW9BcGkxXHNyY1xTd2FnZ2VyRGVtb0FwaVxhcGlcU3VwZXJIZXJvZXM=?=",
  "content-length": "0"

So app.RequireScopes doesn't exists as a workaround as well as AllowAnonymousAccess in the latest IdSvr3.2
Can you please advise.
Tx
