### ISSUE TITLE
NuGet-packages

### ISSUE THREAD

**Issue by johnkors** [IdentityModel/Thinktecture.IdentityModel#86]
Hi, I guess I could infer it from the nuspec files and git tags, but could you add some docs towards these nuget packages? 

https://www.nuget.org/packages/Thinktecture.IdentityModel.WebApi
https://www.nuget.org/packages/Thinktecture.IdentityModel.WebApi.ScopeAuthorization 

The latter seems most recent, but I guess both will be continued after the beta?

Really like the scope auth attributes! Thanks for that.

**Comment by johnkors** [comment]
A little bump on this, as there has been some recent developement and new nugets. Could you add git tags for which commits referring to what NuGet package, similar to what you do idsrv?  

Seeing as this repo is the source of a couple of nugets, it's kinda hard figuring out what commit is in what package. For instance, not sure what commit is in the 4.0.0 release of [Thinktecture.IdentityModel.Client](http://www.nuget.org/packages/Thinktecture.IdentityModel.Client/4.0.0)

Is everything in master deployed as new NuGets?

Or am I missing something, perhaps.

**Comment by leastprivilege** [comment]
Yea - sorry - forgot to tag the Client 4.0.0 - it is https://github.com/IdentityModel/Thinktecture.IdentityModel/commit/663f8232cac51d3d697eaa702a9874cc22e31c13

I want to move the more popular projects so separate repos - but i am a bit time constrained right now.

**Comment by leastprivilege** [comment]
I actually did add a tag - but forgot to push. But are right - it is messy.
